import { CashFlowEntry, FinancialAccount } from './types';

export const financialAccounts: FinancialAccount[] = [
  { id: 'conta-principal', name: 'Conta principal', initialBalance: 15240 },
  { id: 'conta-digital', name: 'Conta digital', initialBalance: 3300 },
  { id: 'caixa-loja', name: 'Caixa da loja', initialBalance: 1200 },
];

export const cashFlowEntries: CashFlowEntry[] = [
  {
    id: 'mov-1',
    date: '2026-03-10',
    description: 'Recebimento de clientes',
    category: 'Receita de servicos',
    accountId: 'conta-principal',
    costCenter: 'Operacional',
    type: 'entrada',
    paymentMethod: 'PIX',
    status: 'realizado',
    value: 1250,
  },
  {
    id: 'mov-2',
    date: '2026-03-10',
    description: 'Compra de produtos',
    category: 'Estoque',
    accountId: 'conta-principal',
    costCenter: 'Vendas',
    type: 'saida',
    paymentMethod: 'Cartao',
    status: 'realizado',
    value: 480,
  },
  {
    id: 'mov-3',
    date: '2026-03-11',
    description: 'Aluguel',
    category: 'Despesa fixa',
    accountId: 'conta-principal',
    costCenter: 'Administrativo',
    type: 'saida',
    paymentMethod: 'Boleto',
    status: 'previsto',
    value: 2000,
  },
  {
    id: 'mov-4',
    date: '2026-03-12',
    description: 'Plano mensal cliente',
    category: 'Receita recorrente',
    accountId: 'conta-digital',
    costCenter: 'Assinaturas',
    type: 'entrada',
    paymentMethod: 'PIX',
    status: 'previsto',
    value: 299,
  },
  {
    id: 'mov-5',
    date: '2026-03-12',
    description: 'Comissao equipe',
    category: 'Folha variavel',
    accountId: 'conta-principal',
    costCenter: 'RH',
    type: 'saida',
    paymentMethod: 'Transferencia',
    status: 'previsto',
    value: 1850,
  },
  {
    id: 'mov-6',
    date: '2026-03-08',
    description: 'Mensalidade consultoria',
    category: 'Receita de servicos',
    accountId: 'conta-principal',
    costCenter: 'Operacional',
    type: 'entrada',
    paymentMethod: 'PIX',
    status: 'realizado',
    value: 4300,
  },
  {
    id: 'mov-7',
    date: '2026-03-09',
    description: 'Pagamento fornecedor embalagens',
    category: 'Insumos',
    accountId: 'conta-digital',
    costCenter: 'Logistica',
    type: 'saida',
    paymentMethod: 'TED',
    status: 'realizado',
    value: 720,
  },
  {
    id: 'mov-8',
    date: '2026-03-13',
    description: 'Impostos municipais',
    category: 'Tributos',
    accountId: 'conta-principal',
    costCenter: 'Fiscal',
    type: 'saida',
    paymentMethod: 'Boleto',
    status: 'vencido',
    value: 960,
  },
  {
    id: 'mov-9',
    date: '2026-03-14',
    description: 'Contrato B2B - parcela 2',
    category: 'Receita de contratos',
    accountId: 'conta-digital',
    costCenter: 'Comercial',
    type: 'entrada',
    paymentMethod: 'Transferencia',
    status: 'previsto',
    value: 5200,
  },
  {
    id: 'mov-10',
    date: '2026-03-16',
    description: 'Folha mensal',
    category: 'Folha fixa',
    accountId: 'conta-principal',
    costCenter: 'RH',
    type: 'saida',
    paymentMethod: 'Transferencia',
    status: 'previsto',
    value: 7300,
  },
  {
    id: 'mov-11',
    date: '2026-03-07',
    description: 'Reembolso de despesa',
    category: 'Outras receitas',
    accountId: 'caixa-loja',
    costCenter: 'Administrativo',
    type: 'entrada',
    paymentMethod: 'Dinheiro',
    status: 'realizado',
    value: 280,
  },
  {
    id: 'mov-12',
    date: '2026-03-06',
    description: 'Frete de fornecedores',
    category: 'Logistica',
    accountId: 'conta-principal',
    costCenter: 'Logistica',
    type: 'saida',
    paymentMethod: 'Cartao',
    status: 'realizado',
    value: 410,
  },
  {
    id: 'mov-13',
    date: '2026-03-05',
    description: 'Campanha de marketing local',
    category: 'Marketing',
    accountId: 'conta-digital',
    costCenter: 'Marketing',
    type: 'saida',
    paymentMethod: 'Cartao',
    status: 'realizado',
    value: 890,
  },
  {
    id: 'mov-14',
    date: '2026-03-04',
    description: 'Receita PDV',
    category: 'Receita de vendas',
    accountId: 'caixa-loja',
    costCenter: 'Vendas',
    type: 'entrada',
    paymentMethod: 'Dinheiro',
    status: 'realizado',
    value: 1370,
  },
];
