import type { PermissionPreset } from './types';

export const PERMISSION_PRESETS: PermissionPreset[] = [
  {
    id: 'receptionist_basic',
    name: 'Recepcionista Basico',
    description: 'Acesso minimo para agendamento e recepcao de clientes.',
    role: 'Receptionist',
    permissions: [
      'schedule.view_general_schedule',
      'schedule.create_appointments',
      'schedule.edit_appointments',
      'schedule.cancel_appointments',
      'schedule.view_available_times',
      'schedule.manage_waitlist',
      'schedule.confirm_arrival',
      'clients.create',
      'clients.view_basic',
      'clients.view_full_history',
      'clients.edit',
      'clients.add_notes',
      'clients.view_preferences',
      'services.view_catalog',
      'services.view_prices',
      'services.sell_services',
      'financial.open_close_cash',
      'financial.register_payments',
      'financial.issue_receipts',
      'financial.view_daily_movement',
      'team.view_own_schedule',
      'team.edit_own_profile',
      'team.change_own_password',
      'reports.view_daily_attendance',
      'reports.view_schedule_overview',
      'communication.view_notifications',
    ],
  },
  {
    id: 'receptionist_full',
    name: 'Recepcionista Completo',
    description: 'Acesso total as funcionalidades de recepcao, incluindo produtos e comunicacao.',
    role: 'Receptionist',
    permissions: [
      'schedule.view_general_schedule',
      'schedule.create_appointments',
      'schedule.edit_appointments',
      'schedule.cancel_appointments',
      'schedule.view_available_times',
      'schedule.manage_waitlist',
      'schedule.confirm_arrival',
      'clients.create',
      'clients.view_basic',
      'clients.view_full_history',
      'clients.edit',
      'clients.add_notes',
      'clients.view_preferences',
      'clients.view_documents',
      'clients.view_payment_history',
      'services.view_catalog',
      'services.view_prices',
      'services.sell_services',
      'services.view_stock',
      'services.sell_products',
      'services.apply_discounts',
      'services.register_additions',
      'financial.open_close_cash',
      'financial.register_payments',
      'financial.register_basic_expenses',
      'financial.issue_receipts',
      'financial.view_daily_movement',
      'team.view_own_schedule',
      'team.request_time_off',
      'team.view_team_schedules',
      'team.internal_communication',
      'team.edit_own_profile',
      'team.change_own_password',
      'reports.view_daily_attendance',
      'reports.view_schedule_overview',
      'reports.view_busy_free_times',
      'reports.view_service_revenue',
      'communication.send_reminders',
      'communication.view_notifications',
      'communication.respond_to_messages',
      'communication.view_communication_history',
    ],
  },
  {
    id: 'barber_basic',
    name: 'Barbeiro Basico',
    description: 'Acesso minimo para gestao da propria agenda e atendimentos.',
    role: 'Barber',
    permissions: [
      'schedule.view_own_schedule',
      'schedule.confirm_arrival',
      'schedule.view_available_times',
      'services.view_catalog',
      'services.view_prices',
      'services.register_services',
      'clients.view_basic',
      'clients.view_own_history',
      'clients.add_notes',
      'clients.view_preferences',
      'team.view_own_schedule',
      'team.edit_own_profile',
      'team.change_own_password',
      'team.view_own_commission',
      'team.view_own_goals',
      'reports.view_daily_attendance',
      'reports.view_schedule_overview',
      'reports.view_personal_productivity',
      'communication.view_notifications',
    ],
  },
  {
    id: 'barber_experienced',
    name: 'Barbeiro Experiente',
    description: 'Acesso ampliado com venda de produtos, visualizacao de estoque e comunicacao com clientes.',
    role: 'Barber',
    permissions: [
      'schedule.view_own_schedule',
      'schedule.confirm_arrival',
      'schedule.view_available_times',
      'services.view_catalog',
      'services.view_prices',
      'services.register_services',
      'services.view_stock',
      'services.sell_products',
      'services.register_additions',
      'clients.view_basic',
      'clients.view_own_history',
      'clients.add_notes',
      'clients.view_preferences',
      'clients.view_documents',
      'clients.view_payment_history',
      'team.view_own_schedule',
      'team.request_time_off',
      'team.view_team_schedules',
      'team.internal_communication',
      'team.edit_own_profile',
      'team.change_own_password',
      'team.view_own_commission',
      'team.view_own_goals',
      'reports.view_daily_attendance',
      'reports.view_schedule_overview',
      'reports.view_personal_productivity',
      'reports.view_busy_free_times',
      'communication.view_notifications',
      'communication.respond_to_messages',
      'communication.view_communication_history',
    ],
  },
];

export const getPresetsByRole = (role: 'Barber' | 'Receptionist'): PermissionPreset[] =>
  PERMISSION_PRESETS.filter((p) => p.role === role);

export const getPresetById = (id: string): PermissionPreset | undefined =>
  PERMISSION_PRESETS.find((p) => p.id === id);
