#!/usr/bin/env node
/**
 * [SMG][D8] export-core — deterministic Financial Domain Core artifact.
 *
 * ADR-016 Amendment-03 (Core Sharing & Integrity Contract): Option B.
 *
 * The D8 Worker Edge Function (Deno) must REUSE the runtime-neutral Financial
 * Domain Core without duplicating it and without relying on the experimental
 * cross-directory bundler feature (Supabase CLI v2.95.6 used in this repo
 * cannot stably import outside supabase/functions/).
 *
 * Solution (PO-approved):
 *   domain/commission/{calculate,participants,types}.ts
 *   shared/numbers/normalize.ts                       <-- SINGLE SOURCE OF TRUTH
 *        |  esbuild (0.25.12, present in this repo) bundles the closure into
 *        v  ONE self-contained Deno-safe .ts module
 *   supabase/functions/_shared/financial-core/index.ts <-- GENERATED ARTIFACT
 *
 * The `_shared` artifact is NEVER edited manually. It is regenerated by
 * `npm run d8:build` and validated byte-for-byte by `npm run d8:verify`
 * (integrity gate). Any divergence -> STOP.
 *
 * Usage:
 *   node scripts/d8/export-core.mjs            # build artifact + manifest
 *   node scripts/d8/export-core.mjs --verify   # integrity gate (STOP on drift)
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '../..');

// ── Canonical source of truth (Amendment-03 §2) ────────────────────────────
const SOURCES = [
  'shared/numbers/normalize.ts',
  'domain/commission/types.ts',
  'domain/commission/calculate.ts',
  'domain/commission/participants.ts',
];

// Public API the worker consumes (Amendment-03 §2). Guarded by the manifest's
// consumerBlobs so an accidental removal fails d8:verify.
const VIRTUAL_ENTRY = `
export {
  // shared/numbers/normalize.ts
  normalizePercentage,
  normalizeRate,
  normalizeParticipantPercentage,
  normalizePercentageValue,
  // domain/commission/types.ts (types only, erased at build)
  // domain/commission/calculate.ts
  resolveCommissionBase,
  detectZeroReason,
  calculateCommissionReversal,
  resolveFinancialBase,
  calculateParticipantPayout,
  calculateParticipantBaseValue,
  calculateTotalPayouts,
  calculateCommissionValue,
  isCommissionEligible,
  getEffectiveRate,
  getDefaultRateForRole,
  // domain/commission/participants.ts
  isSharedExecution,
  isSharedServiceItem,
  buildSoloParticipant,
  hasPartialSavedPayout,
  buildInferredPrimaryParticipant,
  normalizeCommissionParticipants,
  getPrimaryParticipant,
  getAssistantParticipants,
} from 'ENTRY_INTERNAL';
`;

const OUT_DIR = join(repoRoot, 'supabase/functions/_shared/financial-core');
const OUT_FILE = join(OUT_DIR, 'index.ts');
const MANIFEST_FILE = join(OUT_DIR, 'core.sha256.json');

// ── helpers ────────────────────────────────────────────────────────────────
const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

export const canonicalSources = () =>
  SOURCES.map((rel) => ({
    rel,
    abs: resolve(repoRoot, rel),
    sha256: sha256(readFileSync(resolve(repoRoot, rel))),
  }));

// Build the self-contained Deno-safe module into a target file. Pure (no side
// effects) so --verify can rebuild into a temp dir and compare byte-for-byte.
async function buildBundle(outFile) {
  const entry = VIRTUAL_ENTRY.replace(
    "from 'ENTRY_INTERNAL'",
    `from '${resolve(repoRoot, SOURCES[1]).replace(/\\/g, '/')}'`,
  );

  // We need the entry to pull in calculate.ts + participants.ts explicitly so
  // their exports surface. The types.ts re-export is type-only (erased).
  const entryPath = join(repoRoot, 'node_modules/.d8-core-virtual-entry.ts');
  writeFileSync(entryPath, entry, 'utf8');

  try {
    await esbuild.build({
      stdin: {
        contents: `
export * from '${resolve(repoRoot, SOURCES[0]).replace(/\\/g, '/')}';
export * from '${resolve(repoRoot, SOURCES[2]).replace(/\\/g, '/')}';
export * from '${resolve(repoRoot, SOURCES[3]).replace(/\\/g, '/')}';
`,
        resolveDir: repoRoot,
        loader: 'ts',
        sourcefile: 'd8-core.ts',
      },
      bundle: true,
      format: 'esm',
      platform: 'neutral',
      target: ['es2021'],
      outfile: outFile,
      write: true,
      minify: false,
      treeShaking: true,
      logLevel: 'silent',
      // neutralize node/browser-specific package stubs (none expected for pure core)
    });
  } finally {
    try { rmSync(entryPath, { force: true }); } catch (_) {}
  }
}

async function verify() {
  const manifest = JSON.parse(readFileSync(MANIFEST_FILE, 'utf8'));

  // 1. Canonical sources unchanged?
  const current = canonicalSources();
  for (const s of current) {
    const rec = manifest.source.find((x) => x.path === s.rel);
    if (!rec || rec.sha256 !== s.sha256) {
      console.error(
        `D8:VERIFY FAIL — canonical source ${s.rel} changed since last build. ` +
          `Run \`npm run d8:build\` to regenerate the artifact.`,
      );
      process.exit(1);
    }
  }

  // 2. Artifact matches a fresh build byte-for-byte?
  const tmp = join(repoRoot, 'node_modules/.d8-verify-out');
  try { rmSync(tmp, { recursive: true, force: true }); } catch (_) {}
  mkdirSync(tmp, { recursive: true });
  try {
    await buildBundle(join(tmp, 'index.ts'));
    const fresh = readFileSync(join(tmp, 'index.ts'));
    const committed = readFileSync(OUT_FILE);
    if (sha256(fresh) !== sha256(committed)) {
      console.error(
        `D8:VERIFY FAIL — _shared/financial-core/index.ts diverges from canonical ` +
          `Core. It was either edited manually or is stale. Run \`npm run d8:build\`.`,
      );
      process.exit(1);
    }
  } finally {
    try { rmSync(tmp, { recursive: true, force: true }); } catch (_) {}
  }

  // 3. Artifact exposes the expected consumer API surface.
  const committedText = readFileSync(OUT_FILE, 'utf8');
  const missing = manifest.consumerBlobs.filter((name) => !committedText.includes(name));
  if (missing.length > 0) {
    console.error(`D8:VERIFY FAIL — artifact missing exported symbols: ${missing.join(', ')}`);
    process.exit(1);
  }

  console.log('D8:VERIFY OK — canonical Core == worker artifact (byte-identical), API intact.');
}

async function build() {
  const sources = canonicalSources();
  mkdirSync(OUT_DIR, { recursive: true });
  await buildBundle(OUT_FILE);

  // Record the manifest AFTER build so artifact hash matches the emitted file.
  const artifactSha = sha256(readFileSync(OUT_FILE));
  const manifest = {
    contract: 'ADR-016 Amendment-03 (Core Sharing & Integrity Contract)',
    tooling: {
      esbuild: esbuild.version,
      format: 'esm',
      platform: 'neutral',
      target: 'es2021',
      note: 'Self-contained, no relative imports; Deno-safe; bundled by Supabase CLI v2.95.6 within supabase/functions/',
    },
    source: sources.map((s) => ({ path: s.rel, sha256: s.sha256 })),
    artifact: { path: 'supabase/functions/_shared/financial-core/index.ts', sha256: artifactSha },
    consumerBlobs: [
      'normalizePercentage',
      'resolveFinancialBase',
      'calculateCommissionValue',
      'isCommissionEligible',
      'getEffectiveRate',
      'getDefaultRateForRole',
      'normalizeCommissionParticipants',
      'calculateCommissionReversal',
      'detectZeroReason',
    ],
  };
  writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  console.log(
    `D8:BUILD OK — ${sources.length} canonical sources -> ${OUT_REL(OUT_FILE)} (${readFileSync(OUT_FILE).length} bytes).`,
  );
}

function OUT_REL(p) {
  return p.replace(repoRoot + '\\', '').replace(repoRoot + '/', '');
}

const isVerify = process.argv.includes('--verify');
if (isVerify) {
  await verify();
} else {
  await build();
}
