import {
  AlertTriangle,
  BadgeDollarSign,
  BellRing,
  Building2,
  CircleDollarSign,
  LockKeyhole,
  ReceiptText,
  ShieldCheck,
  Users,
} from 'lucide-react';
import {
  AdminActivity,
  AdminFilterState,
  AuditEntry,
  ManagedUserRow,
  QuickAction,
  RiskAlert,
  SubscriptionRequestRow,
  SuperAdminDataset,
} from './types';

const activities: AdminActivity[] = [
  {
    id: 'act-001',
    dateTime: '2026-03-12T09:48:00Z',
    type: 'Alteracao de plano',
    company: 'Studio Prime',
    user: 'Marina Costa',
    origin: 'Portal SaaS',
    status: 'ativo',
    actor: 'Sistema de assinaturas',
    summary: 'Upgrade de Professional para Elite com ativacao imediata.',
    eventType: 'subscription_upgrade',
    notes: 'Validacao antifraude concluida e ciclo atualizado.',
    technicalLog: 'event=subscription_upgrade plan_from=professional plan_to=elite source=billing-engine',
    auditTrail: ['Pedido recebido', 'Pagamento aprovado', 'Plano atualizado', 'Tenant reindexado'],
  },
  {
    id: 'act-002',
    dateTime: '2026-03-12T09:31:00Z',
    type: 'Login suspeito',
    company: 'Barbearia Centro',
    user: 'joao@centro.com',
    origin: 'IP 177.54.20.10',
    status: 'critico',
    actor: 'Monitor de seguranca',
    summary: 'Cinco tentativas falhas em menos de 3 minutos.',
    eventType: 'suspicious_login',
    notes: 'Usuario mantido bloqueado preventivamente.',
    technicalLog: 'event=suspicious_login attempts=5 risk=high device=unknown',
    auditTrail: ['Tentativa 1', 'Tentativa 5', 'Bloqueio preventivo', 'Notificacao enviada'],
  },
  {
    id: 'act-003',
    dateTime: '2026-03-12T08:58:00Z',
    type: 'Pagamento recusado',
    company: 'Espaco Urban',
    user: 'Financeiro tenant',
    origin: 'Gateway PIX',
    status: 'inadimplente',
    actor: 'Motor financeiro',
    summary: 'Falha na liquidacao do boleto de renovacao.',
    eventType: 'payment_failed',
    notes: 'Nova tentativa agendada para 24 horas.',
    technicalLog: 'event=payment_failed invoice=INV-20991 retry=true provider=pix',
    auditTrail: ['Cobranca emitida', 'Falha no pagamento', 'Tenant sinalizado', 'Cobranca reagendada'],
  },
  {
    id: 'act-004',
    dateTime: '2026-03-12T08:16:00Z',
    type: 'Permissao alterada',
    company: 'Glow Clinic',
    user: 'Rafaela Nunes',
    origin: 'Painel master',
    status: 'analise',
    actor: 'Helena Moura',
    summary: 'Permissao ajustada de recepcao para gerente operacional.',
    eventType: 'permission_changed',
    notes: 'Mudanca exige revisao da auditoria devido a acesso financeiro.',
    technicalLog: 'event=permission_changed role_from=receptionist role_to=manager audit_flag=1',
    auditTrail: ['Solicitacao registrada', 'Permissao alterada', 'Auditoria marcada'],
  },
  {
    id: 'act-005',
    dateTime: '2026-03-12T07:42:00Z',
    type: 'Empresa suspensa',
    company: 'Nova Fase',
    user: 'Conta principal',
    origin: 'Painel master',
    status: 'suspenso',
    actor: 'Daniela Rocha',
    summary: 'Tenant suspenso por inadimplencia acima de 21 dias.',
    eventType: 'tenant_suspended',
    notes: 'Acesso bloqueado para todos os usuarios nao administrativos.',
    technicalLog: 'event=tenant_suspended days_overdue=21 hard_lock=true',
    auditTrail: ['Aviso de atraso', 'Bloqueio parcial', 'Suspensao integral'],
  },
  {
    id: 'act-006',
    dateTime: '2026-03-12T07:04:00Z',
    type: 'Usuario criado',
    company: 'Maison Hair',
    user: 'Bianca Lima',
    origin: 'Onboarding',
    status: 'aguardando ativacao',
    actor: 'Sistema de cadastro',
    summary: 'Novo usuario criado aguardando ativacao por e-mail.',
    eventType: 'user_created',
    notes: 'Convite expira em 48 horas.',
    technicalLog: 'event=user_created activation_pending=true invite_expiration=48h',
    auditTrail: ['Conta criada', 'Convite enviado'],
  },
];

const subscriptions: SubscriptionRequestRow[] = [
  {
    id: 'sub-001',
    company: 'Studio Prime',
    owner: 'Marina Costa',
    plan: 'Elite Annual',
    value: 1199,
    paymentMethod: 'Cartao corporativo',
    status: 'ativo',
    requestDate: '2026-03-11',
    dueDate: '2027-03-11',
    history: ['Solicitado em 11/03', 'Pagamento confirmado', 'Upgrade aplicado'],
  },
  {
    id: 'sub-002',
    company: 'Espaco Urban',
    owner: 'Lucas Tavares',
    plan: 'Professional Monthly',
    value: 89.9,
    paymentMethod: 'Boleto',
    status: 'bloqueado',
    requestDate: '2026-03-05',
    dueDate: '2026-03-10',
    history: ['Cobranca enviada', 'Boleto expirado', 'Conta bloqueada'],
  },
  {
    id: 'sub-003',
    company: 'Glow Clinic',
    owner: 'Aline Pires',
    plan: 'Enterprise Custom',
    value: 2490,
    paymentMethod: 'PIX',
    status: 'pendente',
    requestDate: '2026-03-12',
    dueDate: '2026-03-15',
    history: ['Pedido em analise comercial'],
  },
  {
    id: 'sub-004',
    company: 'Nova Fase',
    owner: 'Bruno Leite',
    plan: 'Starter Monthly',
    value: 39.9,
    paymentMethod: 'Cartao',
    status: 'inadimplente',
    requestDate: '2026-02-18',
    dueDate: '2026-03-01',
    history: ['Pagamento recusado', 'Reenvio automatico', 'Tenant sinalizado'],
  },
];

const users: ManagedUserRow[] = [
  {
    id: 'usr-001',
    name: 'Rafaela Nunes',
    company: 'Glow Clinic',
    role: 'Gerente operacional',
    lastAccess: '2026-03-12T09:20:00Z',
    status: 'ativo',
    phone: '(11) 99120-4400',
    email: 'rafaela@glowclinic.com',
    riskLevel: 'baixo',
    history: ['Acesso hoje 09:20', 'Permissao alterada hoje'],
  },
  {
    id: 'usr-002',
    name: 'Joao Andrade',
    company: 'Barbearia Centro',
    role: 'Administrador local',
    lastAccess: '2026-03-12T09:31:00Z',
    status: 'bloqueado',
    phone: '(21) 98888-2211',
    email: 'joao@centro.com',
    riskLevel: 'alto',
    history: ['5 tentativas falhas', 'Bloqueio preventivo'],
  },
  {
    id: 'usr-003',
    name: 'Bianca Lima',
    company: 'Maison Hair',
    role: 'Recepcao',
    lastAccess: '2026-03-11T14:12:00Z',
    status: 'aguardando ativacao',
    phone: '(31) 99912-0080',
    email: 'bianca@maisonhair.com',
    riskLevel: 'medio',
    history: ['Convite enviado', 'Sem ativacao concluida'],
  },
  {
    id: 'usr-004',
    name: 'Carlos Mota',
    company: 'Nova Fase',
    role: 'Financeiro',
    lastAccess: '2026-03-10T18:42:00Z',
    status: 'inativo',
    phone: '(41) 98770-5550',
    email: 'carlos@novafase.com',
    riskLevel: 'medio',
    history: ['Sem acesso ha 2 dias'],
  },
];

const alerts: RiskAlert[] = [
  {
    id: 'alt-001',
    title: 'Pagamentos atrasados',
    description: 'Tenants com cobrancas vencidas e risco de suspensao.',
    count: 12,
    severity: 'alto',
    sla: 'Agir em ate 4h',
    cta: 'Ver empresas',
  },
  {
    id: 'alt-002',
    title: 'Tentativas de login',
    description: 'Usuarios com padrao de acesso fora da curva.',
    count: 7,
    severity: 'alto',
    sla: 'Revisar em 1h',
    cta: 'Ver acessos',
  },
  {
    id: 'alt-003',
    title: 'Solicitacoes antigas',
    description: 'Assinaturas pendentes sem resposta comercial.',
    count: 5,
    severity: 'medio',
    sla: 'Tratar hoje',
    cta: 'Abrir fila',
  },
  {
    id: 'alt-004',
    title: 'Integracoes falhando',
    description: 'Webhook, gateway ou rotina de sincronizacao com erro.',
    count: 3,
    severity: 'alto',
    sla: 'Escalar agora',
    cta: 'Ver erros',
  },
];

const audits: AuditEntry[] = [
  {
    id: 'aud-001',
    actor: 'Helena Moura',
    when: '2026-03-12T09:14:00Z',
    action: 'Alterou permissao de usuario',
    oldValue: 'Recepcao',
    newValue: 'Gerente operacional',
    origin: '187.66.120.14',
    riskLevel: 'medio',
    relatedObject: 'usr-001',
    justification: 'Promocao aprovada pela operacao regional.',
  },
  {
    id: 'aud-002',
    actor: 'Daniela Rocha',
    when: '2026-03-12T07:42:00Z',
    action: 'Suspendeu tenant por inadimplencia',
    oldValue: 'Ativo',
    newValue: 'Suspenso',
    origin: 'Painel master',
    riskLevel: 'alto',
    relatedObject: 'tenant-novafase',
    justification: 'Acima do limite de tolerancia financeira.',
  },
  {
    id: 'aud-003',
    actor: 'Sistema de seguranca',
    when: '2026-03-12T09:31:00Z',
    action: 'Bloqueio preventivo de acesso',
    oldValue: 'Ativo',
    newValue: 'Bloqueado',
    origin: '177.54.20.10',
    riskLevel: 'alto',
    relatedObject: 'usr-002',
    justification: 'Padrao de risco detectado automaticamente.',
  },
];

const quickActions: QuickAction[] = [
  { id: 'qa-001', label: 'Bloquear usuario', description: 'Interrompe acesso imediatamente.', tone: 'danger' },
  { id: 'qa-002', label: 'Desbloquear usuario', description: 'Reativa acesso com trilha de auditoria.', tone: 'success' },
  { id: 'qa-003', label: 'Suspender empresa', description: 'Congela operacao do tenant.', tone: 'danger' },
  { id: 'qa-004', label: 'Reativar empresa', description: 'Retoma acesso e sincroniza permissoes.', tone: 'success' },
  { id: 'qa-005', label: 'Aprovar assinatura', description: 'Conclui fila comercial.', tone: 'default' },
  { id: 'qa-006', label: 'Criar plano', description: 'Abre configuracao de novo pacote.', tone: 'default' },
  { id: 'qa-007', label: 'Visualizar logs', description: 'Acesso a eventos tecnicos.', tone: 'default' },
  { id: 'qa-008', label: 'Gerar relatorio', description: 'Exporta dados filtrados.', tone: 'default' },
  { id: 'qa-009', label: 'Acessar suporte', description: 'Abre fila de tickets globais.', tone: 'default' },
  { id: 'qa-010', label: 'Central de auditoria', description: 'Abre trilha administrativa.', tone: 'default' },
];

export const defaultAdminFilters: AdminFilterState = {
  period: '7d',
  company: 'all',
  status: 'all',
  movementType: 'all',
  plan: 'all',
  user: 'all',
  financial: 'all',
  blockedState: 'all',
};

export const adminFilterOptions = {
  periods: [
    { value: '24h', label: 'Ultimas 24h' },
    { value: '7d', label: 'Ultimos 7 dias' },
    { value: '30d', label: 'Ultimos 30 dias' },
    { value: '90d', label: 'Ultimos 90 dias' },
  ],
  companies: [
    { value: 'all', label: 'Todas empresas' },
    { value: 'Studio Prime', label: 'Studio Prime' },
    { value: 'Glow Clinic', label: 'Glow Clinic' },
    { value: 'Nova Fase', label: 'Nova Fase' },
    { value: 'Barbearia Centro', label: 'Barbearia Centro' },
  ],
  statuses: [
    { value: 'all', label: 'Todos status' },
    { value: 'ativo', label: 'Ativo' },
    { value: 'pendente', label: 'Pendente' },
    { value: 'bloqueado', label: 'Bloqueado' },
    { value: 'inadimplente', label: 'Inadimplente' },
    { value: 'critico', label: 'Critico' },
  ],
  movementTypes: [
    { value: 'all', label: 'Todas movimentacoes' },
    { value: 'Alteracao de plano', label: 'Alteracao de plano' },
    { value: 'Login suspeito', label: 'Login suspeito' },
    { value: 'Pagamento recusado', label: 'Pagamento recusado' },
    { value: 'Permissao alterada', label: 'Permissao alterada' },
  ],
  plans: [
    { value: 'all', label: 'Todos planos' },
    { value: 'Starter Monthly', label: 'Starter Monthly' },
    { value: 'Professional Monthly', label: 'Professional Monthly' },
    { value: 'Elite Annual', label: 'Elite Annual' },
    { value: 'Enterprise Custom', label: 'Enterprise Custom' },
  ],
  users: [
    { value: 'all', label: 'Todos usuarios' },
    { value: 'Rafaela Nunes', label: 'Rafaela Nunes' },
    { value: 'Joao Andrade', label: 'Joao Andrade' },
    { value: 'Bianca Lima', label: 'Bianca Lima' },
  ],
  financialStates: [
    { value: 'all', label: 'Toda situacao financeira' },
    { value: 'regular', label: 'Regular' },
    { value: 'inadimplente', label: 'Inadimplente' },
    { value: 'aguardando pagamento', label: 'Aguardando pagamento' },
  ],
  blockedStates: [
    { value: 'all', label: 'Todos' },
    { value: 'blocked', label: 'Bloqueados' },
    { value: 'unblocked', label: 'Desbloqueados' },
  ],
};

export const createSuperAdminDataset = (): SuperAdminDataset => ({
  kpis: [
    {
      id: 'kpi-001',
      title: 'Empresas ativas',
      value: '248',
      delta: '+8,3%',
      context: '237 tenants operando no ultimo ciclo',
      icon: Building2,
      tone: 'gold',
    },
    {
      id: 'kpi-002',
      title: 'Usuarios ativos hoje',
      value: '1.482',
      delta: '+12%',
      context: '74% da base ativa diaria',
      icon: Users,
      tone: 'emerald',
    },
    {
      id: 'kpi-003',
      title: 'Assinaturas pendentes',
      value: '19',
      delta: '6 exigem analise',
      context: 'Fila comercial aguardando decisao',
      icon: ReceiptText,
      tone: 'blue',
    },
    {
      id: 'kpi-004',
      title: 'Assinaturas inadimplentes',
      value: '12',
      delta: 'R$ 8.940 em aberto',
      context: 'Risco financeiro concentrado em 4 tenants',
      icon: BadgeDollarSign,
      tone: 'red',
    },
    {
      id: 'kpi-005',
      title: 'Usuarios bloqueados',
      value: '31',
      delta: '+4 nas ultimas 24h',
      context: '17 bloqueios preventivos automaticos',
      icon: LockKeyhole,
      tone: 'red',
    },
    {
      id: 'kpi-006',
      title: 'Solicitacoes recentes',
      value: '54',
      delta: '+11 hoje',
      context: 'Entrada de upgrade, cancelamento e suporte',
      icon: BellRing,
      tone: 'slate',
    },
    {
      id: 'kpi-007',
      title: 'Alertas criticos',
      value: '9',
      delta: '3 exigem escalacao',
      context: 'Prioridade alta em seguranca e integracao',
      icon: AlertTriangle,
      tone: 'red',
    },
    {
      id: 'kpi-008',
      title: 'MRR estimado',
      value: 'R$ 186.240',
      delta: '+6,8%',
      context: 'Receita recorrente do ciclo atual',
      icon: CircleDollarSign,
      tone: 'gold',
    },
  ],
  activities,
  subscriptions,
  users,
  alerts,
  audits,
  quickActions,
  lastUpdatedAt: new Date().toISOString(),
});

export const overviewHealthCards = [
  {
    id: 'health-001',
    title: 'Integridade operacional',
    value: '97,2%',
    description: 'Processamentos concluindo dentro do SLA.',
    icon: ShieldCheck,
  },
  {
    id: 'health-002',
    title: 'Fila critica',
    value: '14 itens',
    description: 'Demandas com impacto direto em receita e acesso.',
    icon: AlertTriangle,
  },
];

export const formatCurrency = (value: number) =>
  new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);

export const cloneDataset = () => createSuperAdminDataset();
