BEGIN;

ALTER TABLE IF EXISTS public.suppliers
  ADD COLUMN IF NOT EXISTS document TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT;

ALTER TABLE IF EXISTS barber.suppliers
  ADD COLUMN IF NOT EXISTS document TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT;

COMMIT;
