import type { EntityConfig } from '../types';

export const productsConfig: EntityConfig = {
  entity: 'products',
  label: 'Produto',
  labelPlural: 'Produtos',
  tableName: 'products',
  idField: 'id',
  requiredColumns: ['Nome', 'Preço de Venda'],
  optionalColumns: [
    'Código',
    'Categoria',
    'Fornecedor',
    'Preço de Custo',
    'Estoque Atual',
    'Estoque Mínimo',
    'Código de Barras',
    'Ativo',
    'Descrição',
  ],
  columnMapping: {
    'Código': 'code',
    'Nome': 'name',
    'Categoria': 'category',
    'Fornecedor': 'supplier',
    'Preço de Custo': 'cost_price',
    'Preço de Venda': 'sale_price',
    'Estoque Atual': 'stock_quantity',
    'Estoque Mínimo': 'minimum_stock',
    'Código de Barras': 'barcode',
    'Ativo': 'active',
    'Descrição': 'description',
  },
  validationRules: {
    name: { type: 'string', minLength: 2, required: true },
    code: { type: 'string', minLength: 1 },
    sale_price: { type: 'number', min: 0, required: true },
    cost_price: { type: 'number', min: 0 },
    stock_quantity: { type: 'integer', min: 0 },
    minimum_stock: { type: 'integer', min: 0 },
    commission: { type: 'number', min: 0, max: 100 },
    active: { type: 'boolean' },
  },
  normalizationRules: {
    name: { trim: true, title_case: true },
    code: { trim: true, upper: true },
    category: { trim: true },
    supplier: { trim: true },
    sale_price: { currency_br: true },
    cost_price: { currency_br: true },
    stock_quantity: { integer: true },
    minimum_stock: { integer: true },
    barcode: { trim: true },
    description: { trim: true },
    active: { trim: true },
  },
  duplicateCheckFields: ['code', 'barcode'],
  defaultAction: 'create',
};