import type { EntityConfig } from '../types';

export const servicesConfig: EntityConfig = {
  entity: 'services',
  label: 'Serviço',
  labelPlural: 'Serviços',
  tableName: 'services',
  idField: 'id',
  requiredColumns: ['Nome', 'Preço'],
  optionalColumns: [
    'Código',
    'Categoria',
    'Duração (min)',
    'Comissão (%)',
    'Descrição',
    'Ativo',
  ],
  columnMapping: {
    'Código': 'code',
    'Nome': 'name',
    'Categoria': 'category',
    'Duração (min)': 'duration',
    'Preço': 'price',
    'Comissão (%)': 'commission',
    'Descrição': 'description',
    'Ativo': 'active',
  },
  validationRules: {
    name: { type: 'string', minLength: 2, required: true },
    code: { type: 'string', minLength: 1 },
    price: { type: 'number', min: 0, required: true },
    duration: { type: 'integer', min: 1, max: 480 },
    commission: { type: 'number', min: 0, max: 100 },
    active: { type: 'boolean' },
    description: { type: 'string' },
  },
  normalizationRules: {
    name: { trim: true, title_case: true },
    code: { trim: true, upper: true },
    category: { trim: true },
    price: { currency_br: true },
    duration: { integer: true },
    commission: { percentage: true },
    description: { trim: true },
    active: { trim: true },
  },
  duplicateCheckFields: ['code', 'name'],
  defaultAction: 'create',
};